---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: {{HOMEPAGE_VAR_TITLE}} # Homepage title
favicon: {{HOMEPAGE_VAR_FAVICON}} # Homepage favicon
color: slate
headerStyle: underlined
target: _blank
hideVersion: true
showStats: true
statusStyle: "dot"

layout:
  Media:
    style: row
    columns: 2
    useEqualHeights: true

  Tools:
    style: row
    columns: 2
    useEqualHeights: true

  Indexers:
    style: row
    columns: 3
    useEqualHeights: true

  Downloaders:
    style: row
    columns: 2
    useEqualHeights: true
